In [12]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def train_logistic(X, y, lr=0.1, epochs=1000):
    m, n = X.shape
    print(m,n)
    weights = np.zeros(n)  # Initialize weights for features (excluding bias)
    bias = 0.0  # Separate bias term

    for epoch in range(epochs):
        # Linear combination for z (including separate bias term)
        z = np.dot(X, weights) + bias  # We now add the bias separately
        
        # Predicted probabilities using sigmoid
        predictions = sigmoid(z)

        # Calculate gradients for weights and bias
        gradient_weights = (1/m) * np.dot(X.T, (predictions - y))  # Gradient for weights
        gradient_bias = (1/m) * np.sum(predictions - y)  # Gradient for bias

        # Update weights and bias using gradient descent
        weights -= lr * gradient_weights
        bias -= lr * gradient_bias

        # Print variables at specific intervals for monitoring
        loss = -np.mean(y * np.log(predictions + 1e-15) + (1 - y) * np.log(1 - predictions + 1e-15))
            
        print(f"Epoch {epoch}")
        print(f"  Weights: {weights}")
        print(f"  Bias: {bias}")
        print(f"  Z: {z}")
        print(f" actual{y}")
        print(f"  Predictions: {predictions}")
        print(f"{predictions - y}")
        print(f"  Gradient for Weights: {gradient_weights}")
        print(f"  Gradient for Bias: {gradient_bias}")
        print(f"  Loss: {loss:.4f}")
        print("-" * 50) 
            

    return weights, bias  # Return both weights and bias

# Example usage:
X = np.array([[0], [1], [3], [4]])  # Example input
y = np.array([1, 1, 0, 0])  # Example labels

weights, bias = train_logistic(X, y, lr=0.1, epochs=1000)
print("Final Weights:", weights)
print("Final Bias:", bias)


4 1
Epoch 0
  Weights: [-0.075]
  Bias: 0.0
  Z: [0. 0. 0. 0.]
 actual[1 1 0 0]
  Predictions: [0.5 0.5 0.5 0.5]
[-0.5 -0.5  0.5  0.5]
  Gradient for Weights: [0.75]
  Gradient for Bias: 0.0
  Loss: 0.6931
--------------------------------------------------
Epoch 1
  Weights: [-0.13788618]
  Bias: 0.0037299405808703515
  Z: [ 0.    -0.075 -0.225 -0.3  ]
 actual[1 1 0 0]
  Predictions: [0.5        0.48125878 0.44398611 0.42555748]
[-0.5        -0.51874122  0.44398611  0.42555748]
  Gradient for Weights: [0.62886176]
  Gradient for Bias: -0.037299405808703515
  Loss: 0.6415
--------------------------------------------------
Epoch 2
  Weights: [-0.1911058]
  Bias: 0.010411329805914218
  Z: [ 0.00372994 -0.13415624 -0.40992859 -0.54781476]
 actual[1 1 0 0]
  Predictions: [0.50093248 0.46651115 0.39892924 0.36637155]
[-0.49906752 -0.53348885  0.39892924  0.36637155]
  Gradient for Weights: [0.53219627]
  Gradient for Bias: -0.06681389225043866
  Loss: 0.6048
---------------------------------