In [3]:
import numpy as np

q1=np.array([
    [10,20,30],
    [30,20,30],
    [40,50,20]])

q2=np.array([
    [30,20,30],
    [20,70,30],
    [40,50,20]])

price=np.array([
    [2,3,4],
    [1,3,4],
    [2,7,4]
])

total_sales=q2+q1

totalRevenue=((total_sales*price))
totalDiscount=totalRevenue*0.2
netRevenue=totalRevenue-totalDiscount
netRevenueSum= np.sum(netRevenue);

q1percentSale=(q1/total_sales)*100
q2percentSale=(q2/total_sales)*100

growthP= (q2-q1)*100/q1

print(netRevenue)



[[ 64.  96. 192.]
 [ 40. 216. 192.]
 [128. 560. 128.]]


In [4]:
houses=np.array([
    [200,3],
    [150,4]
])

weight=np.array(
    [150,2000]
)

estimatedHousePrice= np.dot(houses,weight.T)
print(estimatedHousePrice)

[36000 30500]
