In [2]:
import numpy as np

In [3]:


# Array Creation

a=np.array([1,2,3,4,5])
a


array([1, 2, 3, 4, 5])

In [8]:
#custonm array creation
a1=np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
a2=np.arange(10,30)
a2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [38]:
a3=np.linspace(10,5,15)
a3

array([10.        ,  9.64285714,  9.28571429,  8.92857143,  8.57142857,
        8.21428571,  7.85714286,  7.5       ,  7.14285714,  6.78571429,
        6.42857143,  6.07142857,  5.71428571,  5.35714286,  5.        ])

In [44]:
a4=np.array([np.ones((2,3))])
a4.ndim

3

In [58]:
# datatype 
a4.dtype

dtype('int64')

In [53]:
a4=a4.astype("int")
a4.dtype

dtype('int64')

In [54]:
#array size
a4.size

6

In [55]:
a4.itemsize

8

In [56]:
#array shape
a4.shape

(1, 2, 3)

In [57]:
a4=a4.reshape(-1-1,2)
a4

array([[1, 1],
       [1, 1],
       [1, 1]])

In [66]:
# iteration on the array
for x in np.nditer(a4):
    print(x)

1
1
1
1
1
1


In [67]:
for index,x in np.ndenumerate(a4):
    print(index,x)

(0, 0) 1
(0, 1) 1
(1, 0) 1
(1, 1) 1
(2, 0) 1
(2, 1) 1


In [88]:
a5=np.arange(0,40)
a6=np.arange(40,80)

a5=a5.reshape(-1,5)
a6=a6.reshape(-1,5)

print(a5,a6)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]] [[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]]


In [89]:
#concating array
a7=np.hstack((a5,a6))
a7

array([[ 0,  1,  2,  3,  4, 40, 41, 42, 43, 44],
       [ 5,  6,  7,  8,  9, 45, 46, 47, 48, 49],
       [10, 11, 12, 13, 14, 50, 51, 52, 53, 54],
       [15, 16, 17, 18, 19, 55, 56, 57, 58, 59],
       [20, 21, 22, 23, 24, 60, 61, 62, 63, 64],
       [25, 26, 27, 28, 29, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 70, 71, 72, 73, 74],
       [35, 36, 37, 38, 39, 75, 76, 77, 78, 79]])

In [86]:
a8=np.vstack((a5,a6))
a8

array([[40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79]])

In [95]:
# spliting array
a5,a6=np.hsplit(a7,2)
print(a5,a6)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]] [[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]]


In [96]:
a5,a6=np.vsplit(a7,2)
print(a5,a6)

[[ 0  1  2  3  4 40 41 42 43 44]
 [ 5  6  7  8  9 45 46 47 48 49]
 [10 11 12 13 14 50 51 52 53 54]
 [15 16 17 18 19 55 56 57 58 59]] [[20 21 22 23 24 60 61 62 63 64]
 [25 26 27 28 29 65 66 67 68 69]
 [30 31 32 33 34 70 71 72 73 74]
 [35 36 37 38 39 75 76 77 78 79]]


In [98]:
#array sorting
s=np.sort(a5)
s

array([[ 0,  1,  2,  3,  4, 40, 41, 42, 43, 44],
       [ 5,  6,  7,  8,  9, 45, 46, 47, 48, 49],
       [10, 11, 12, 13, 14, 50, 51, 52, 53, 54],
       [15, 16, 17, 18, 19, 55, 56, 57, 58, 59]])

In [109]:
# array filtering

filtered=s[s>5]
filtered

array([40, 41, 42, 43, 44,  6,  7,  8,  9, 45, 46, 47, 48, 49, 10, 11, 12,
       13, 14, 50, 51, 52, 53, 54, 15, 16, 17, 18, 19, 55, 56, 57, 58, 59])

In [ ]:
#math function on array
s.sum(axis=0)
