In [46]:
import numpy as np

myarr=np.array([
    
    [1,2,3,4,5],
    [6,2,5,1,9],
    [6,2,5,3,4]
    
])

print(myarr[:,2:])

[[3 4 5]
 [5 1 9]
 [5 3 4]]


In [94]:
# Custumor id,name
a=np.array([
    [101,"ali"],
     [102,"abdul"],
     [103,"samad"]
])

# Custumor id,pushase amount , purchase Date

b=np.array([
    [104,250.50,"2024"],
     [105,200.30,"2024"],
     [106,150.30,"2011"]
])

mytemp=np.hstack((a,b))
g,h,temp2=np.hsplit(b,3)
d=np.hstack((mytemp,temp2))
a1,a2,e=np.vsplit(d,3)




print(a)
print(b)
print(c)
print(d)


[['101' 'ali']
 ['102' 'abdul']
 ['103' 'samad']]
[['104' '250.5' '2024']
 ['105' '200.3' '2024']
 ['106' '150.3' '2011']]
[['2024' '2024' '2011']
 ['2024' '2024' '2011']]
[['101' 'ali' '104' '250.5' '2024' '2024']
 ['102' 'abdul' '105' '200.3' '2024' '2024']
 ['103' 'samad' '106' '150.3' '2011' '2011']]


In [101]:
#condition based array
arr=np.array([
    
    [1,2,3,4,5],
    [6,2,5,1,9],
    [6,2,5,3,4]
    
])

condition=arr>4
print(condition)

print(arr[condition])


[[False False False False  True]
 [ True False  True False  True]
 [ True False  True False False]]
[5 6 5 9 6 5]


In [127]:
values=np.array([10,12,4,15,8])
index=np.argmax(values)
print(index)

transactions= np.array([
    ['101','mohan1','250.5','2024-09-01'],
    ['102','mohan2','33.5','2029-09-01'],
    ['103','mohan3','2343.5','2026-09-01'],
    ['104','mohan4','55.5','2024-09-01'],
    ['105','mohan5','250.5','2022-09-01'],
    
])

index=np.argmax(transactions[:,2].astype(float))
HighestSalaryperson=transactions[index,:]

index1=transactions[transactions[:,0] == "101"]
print(index1)

3
[['101' 'mohan1' '250.5' '2024-09-01']]
